.TH DILLO 1 
.SH NAME
dillo \- GTK-based web browser
.SH SYNOPSIS
.B dillo
[url]
.SH DESCRIPTION
This manual page documents briefly the
.BR dillo
command.
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.PP
.B dillo
is based on
.B gzilla
and is a free browser which uses the GTK.
.SH OPTIONS
There are no options.  Pass a URL on the command line to open the
browser at that location.
.SH EXAMPLES
.I /etc/dillorc
is a sample
.IR ~/.dillo/dillorc .
.SH FILES
.I ~/.dillo/dillorc
.br
.I ~/.dillo/bookmarks.html
.SH AUTHOR
.B dillo
was created by the Dillo project.  More information can be found on
the project home page:
.IP
http://www.dillo.org
.PP
This man page was created by Ron Farrer <rbf@debian.org> for the
Debian GNU/Linux distribution.
